name: Python CI/CD

on:
  push:
    branches: [ cryptoGestion ]
  pull_request:
    branches: [ cryptoGestion ]
  workflow_dispatch:

jobs:
 
  lint:
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            docker-compose.yml


      - name: Docker
        run: |
          docker build -t cryptoimage .
          docker compose up -d
